"""empty message

Revision ID: 929dec5f7754
Revises: 2568f6497425
Create Date: 2026-04-25 20:19:43.377050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929dec5f7754'
down_revision = '2568f6497425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
