"""added title

Revision ID: bb7227adf17b
Revises: 2a45456a8ca7
Create Date: 2026-04-20 23:18:58.021312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7227adf17b'
down_revision = '2a45456a8ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
